"""OpenWRT SQM configuration generator."""

from typing import Optional
from pathlib import Path
import logging

from ipo.core.utils.logging import get_logger

logger = get_logger(__name__)


class OpenWRTGenerator:
    """Generate OpenWRT SQM (Smart Queue Management) configurations."""
    
    def __init__(
        self,
        download_mbps: float,
        upload_mbps: float,
        interface: str = "eth1",  # Common WAN interface
        overhead: int = 44  # Common overhead for PPPoE/VDSL
    ):
        """
        Initialize OpenWRT SQM generator.
        
        Args:
            download_mbps: Download bandwidth in Mbps
            upload_mbps: Upload bandwidth in Mbps
            interface: WAN interface name
            overhead: Protocol overhead in bytes (44 for PPPoE, 18 for cable)
        """
        self.download_mbps = download_mbps
        self.upload_mbps = upload_mbps
        self.interface = interface
        self.overhead = overhead
        self.logger = get_logger(f"{__name__}.OpenWRTGenerator")
    
    def _calculate_kbps(self, mbps: float, margin: float = 0.95) -> int:
        """
        Calculate kbps with safety margin.
        
        Args:
            mbps: Speed in Mbps
            margin: Safety margin (0.95 = 95% of line speed)
        
        Returns:
            Speed in kbps with margin applied
        """
        return int(mbps * 1000 * margin)
    
    def generate_uci_commands(self, margin: float = 0.95) -> str:
        """
        Generate UCI commands for OpenWRT SQM configuration.
        
        Args:
            margin: Safety margin for bandwidth (0.95 = use 95% of line speed)
        
        Returns:
            UCI commands as string
        """
        download_kbps = self._calculate_kbps(self.download_mbps, margin)
        upload_kbps = self._calculate_kbps(self.upload_mbps, margin)
        
        self.logger.info(
            f"Generating OpenWRT SQM config: {download_kbps} kbps down, "
            f"{upload_kbps} kbps up on {self.interface}"
        )
        
        commands = f"""#!/bin/sh
# OpenWRT SQM Configuration
# Generated by Internet Performance Optimizer
# 
# Connection: {self.download_mbps} Mbps down / {self.upload_mbps} Mbps up
# Interface: {self.interface}
# Safety margin: {margin * 100:.0f}%
#
# Installation:
# 1. SSH into your OpenWRT router
# 2. Copy and paste these commands
# 3. Verify with: uci show sqm

# Install SQM package if not already installed
# opkg update
# opkg install sqm-scripts

# Remove any existing SQM configuration
uci delete sqm.@queue[0] 2>/dev/null
uci commit sqm

# Create new SQM configuration
uci add sqm queue
uci set sqm.@queue[-1].enabled='1'
uci set sqm.@queue[-1].interface='{self.interface}'
uci set sqm.@queue[-1].qdisc='cake'
uci set sqm.@queue[-1].script='piece_of_cake.qos'

# Download settings (ingress)
uci set sqm.@queue[-1].download='{download_kbps}'

# Upload settings (egress)
uci set sqm.@queue[-1].upload='{upload_kbps}'

# CAKE options for optimal bufferbloat reduction
uci set sqm.@queue[-1].qdisc_advanced='1'
uci set sqm.@queue[-1].squash_dscp='1'
uci set sqm.@queue[-1].squash_ingress='1'
uci set sqm.@queue[-1].ingress_ecn='ECN'
uci set sqm.@queue[-1].egress_ecn='ECN'

# Link layer adaptation for overhead
uci set sqm.@queue[-1].linklayer='ethernet'
uci set sqm.@queue[-1].overhead='{self.overhead}'

# Advanced CAKE options
uci set sqm.@queue[-1].iqdisc_opts='diffserv4 nat dual-dsthost'
uci set sqm.@queue[-1].eqdisc_opts='diffserv4 nat dual-srchost ack-filter'

# Commit and restart
uci commit sqm
/etc/init.d/sqm restart

echo "SQM configuration applied!"
echo "Run 'bufferbloat test' to verify improvement"
"""
        
        return commands
    
    def generate_config_file(self, margin: float = 0.95) -> str:
        """
        Generate complete SQM config file.
        
        Args:
            margin: Safety margin for bandwidth
        
        Returns:
            Complete config file content
        """
        download_kbps = self._calculate_kbps(self.download_mbps, margin)
        upload_kbps = self._calculate_kbps(self.upload_mbps, margin)
        
        config = f"""# SQM Configuration for OpenWRT
# Generated by Internet Performance Optimizer

config queue
	option enabled '1'
	option interface '{self.interface}'
	option qdisc 'cake'
	option script 'piece_of_cake.qos'
	option download '{download_kbps}'
	option upload '{upload_kbps}'
	option qdisc_advanced '1'
	option squash_dscp '1'
	option squash_ingress '1'
	option ingress_ecn 'ECN'
	option egress_ecn 'ECN'
	option linklayer 'ethernet'
	option overhead '{self.overhead}'
	option iqdisc_opts 'diffserv4 nat dual-dsthost'
	option eqdisc_opts 'diffserv4 nat dual-srchost ack-filter'
"""
        
        return config
    
    def save_uci_script(self, output_path: Path, margin: float = 0.95) -> Path:
        """
        Save UCI commands to shell script.
        
        Args:
            output_path: Output file path
            margin: Safety margin for bandwidth
        
        Returns:
            Path to saved file
        """
        script = self.generate_uci_commands(margin)
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(script)
        
        # Make executable on Unix-like systems
        try:
            import stat
            output_path.chmod(output_path.stat().st_mode | stat.S_IEXEC)
        except Exception:
            pass
        
        self.logger.info(f"Saved OpenWRT SQM script to: {output_path}")
        return output_path
    
    def save_config(self, output_path: Path, margin: float = 0.95) -> Path:
        """
        Save config file.
        
        Args:
            output_path: Output file path
            margin: Safety margin for bandwidth
        
        Returns:
            Path to saved file
        """
        config = self.generate_config_file(margin)
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(config)
        
        self.logger.info(f"Saved OpenWRT SQM config to: {output_path}")
        return output_path
    
    @staticmethod
    def get_usage_instructions() -> str:
        """Get instructions for using the generated configuration."""
        return """
OpenWRT SQM Configuration Instructions:

1. Determine your connection speed:
   - Run speed test: https://www.waveform.com/tools/bufferbloat
   - Note download and upload speeds

2. Generate configuration:
   ipo router openwrt --download YOUR_DOWN --upload YOUR_UP --output sqm.sh

3. Apply to your OpenWRT router:
   # SSH into router
   ssh root@192.168.1.1
   
   # Copy the generated script
   # Then paste and run it
   
4. Verify configuration:
   uci show sqm
   
5. Test bufferbloat improvement:
   - Run: ipo bench --target 1.1.1.1
   - Compare before/after bufferbloat grades

6. Fine-tuning:
   - If you still see bufferbloat, reduce speeds by 5-10%
   - Adjust margin: ipo router openwrt --download X --upload Y --margin 0.90

7. Rollback if needed:
   uci delete sqm.@queue[0]
   uci commit sqm
   /etc/init.d/sqm restart

For more information:
- OpenWRT SQM: https://openwrt.org/docs/guide-user/network/traffic-shaping/sqm
- Bufferbloat: https://www.bufferbloat.net/
"""


def generate_openwrt_config(
    download_mbps: float,
    upload_mbps: float,
    output: Optional[Path] = None,
    interface: str = "eth1",
    margin: float = 0.95
) -> str:
    """
    Convenience function to generate OpenWRT SQM configuration.
    
    Args:
        download_mbps: Download bandwidth
        upload_mbps: Upload bandwidth
        output: Optional output file path
        interface: WAN interface name
        margin: Safety margin (0.95 = 95% of line speed)
    
    Returns:
        Configuration commands as string
    """
    generator = OpenWRTGenerator(
        download_mbps=download_mbps,
        upload_mbps=upload_mbps,
        interface=interface
    )
    
    commands = generator.generate_uci_commands(margin=margin)
    
    if output:
        generator.save_uci_script(Path(output), margin=margin)
    
    return commands
