#!/bin/sh
# OpenWRT SQM Configuration
# Generated by Internet Performance Optimizer v0.1.0
# 
# Connection: 100.0 Mbps down / 20.0 Mbps up
# Interface: eth1
# Safety margin: 95%
#
# Installation:
# 1. SSH into your OpenWRT router
# 2. Copy and paste these commands
# 3. Verify with: uci show sqm

# Install SQM package if not already installed
# opkg update
# opkg install sqm-scripts

# Remove any existing SQM configuration
uci delete sqm.@queue[0] 2>/dev/null
uci commit sqm

# Create new SQM configuration
uci add sqm queue
uci set sqm.@queue[-1].enabled='1'
uci set sqm.@queue[-1].interface='eth1'
uci set sqm.@queue[-1].qdisc='cake'
uci set sqm.@queue[-1].script='piece_of_cake.qos'

# Download settings (ingress)
uci set sqm.@queue[-1].download='95000'

# Upload settings (egress)
uci set sqm.@queue[-1].upload='19000'

# CAKE options for optimal bufferbloat reduction
uci set sqm.@queue[-1].qdisc_advanced='1'
uci set sqm.@queue[-1].squash_dscp='1'
uci set sqm.@queue[-1].squash_ingress='1'
uci set sqm.@queue[-1].ingress_ecn='ECN'
uci set sqm.@queue[-1].egress_ecn='ECN'

# Link layer adaptation for overhead
uci set sqm.@queue[-1].linklayer='ethernet'
uci set sqm.@queue[-1].overhead='44'

# Advanced CAKE options
uci set sqm.@queue[-1].iqdisc_opts='diffserv4 nat dual-dsthost'
uci set sqm.@queue[-1].eqdisc_opts='diffserv4 nat dual-srchost ack-filter'

# Commit and restart
uci commit sqm
/etc/init.d/sqm restart

echo "SQM configuration applied!"
echo "Run 'bufferbloat test' to verify improvement"
